### ISSUE TITLE
Release of Python-Mapswipe-Workers 2.0

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#102]
# Release Python-Mapwipe-Workers 2.0

This release will extend MapSwipe with new functionalities for change detection in satellite imagery and will improve maintainability, efficiency and performance.

## Isues
- [x] Firebase Database Structure: V2 #132 
- [x] Firebase: Improve Realtime Database data structure #97 
- [x] Firebase: Use Firebase Functions to reduce data transfer between Firebase and Python-Mapswipe-Workers #98 
- [x] Firebase: Adjust firebase rules to new data structure #124 
- [x] Mapswipe Workers: Improve class hierarchy using Abstract Base Classes (ABCs) #106
- [x] Mapswipe Workers: Rewrite firebase_to_postgres package (transfer_results.py and update.py) #121
- [x] Mapswipe Workers: Rewrite generate_stats.py #120 
- [x] Mapswipe-Workers: Rewrite docker-compose.yaml #123
- [x] Improve handling of logs on the server #114 
- [x] Postgres: Improve database schema #99
- [x] Import Formular: Change attribute name in import formular #119 
- [x] Documentation: Extend docs with diagrams #96 
- [x] Documentation: How to add a new project? #67 

## Transition
This release will break backward compatibility with old versions of the App. There will be a transition time during which both backends and versions of the app will be supported. But new projects will only be created using MapSwipe 2.0.

- [x] Add to database.rules.json (dev-branch) the current production database rules. Make sure v1 and v2 are supported
- [x] Tranform data of the Firebase Realtime Database to fit the new data structure
    - [x] transfer data for projects, groups and tasks to new production database on a project basis
    - [x] transfer data for results to new production database
- [x] Backup routine #110 
    - Restore backup at least once
- [x] Setup Lets Encrypt  #159
- [x] Publish the new App in the Google Play Store and in the App Store
    - https://github.com/mapswipe/mapswipe/issues/44
    - https://github.com/mapswipe/mapswipe/issues/43
