### ISSUE TITLE
Designs for tutorial creation

### ISSUE THREAD

**Issue by udaynwa** [mapswipe/python-mapswipe-workers#796]
### Tasks 

- [x] Wireframes for `build-area`
- [x] Wireframes for `footprint`
- [x] Wireframes for `change detection`
- [x] Wireframes for `completeness`
