### ISSUE TITLE
Improve tutorial creation workflow

### ISSUE THREAD

**Issue by udaynwa** [mapswipe/python-mapswipe-workers#798]
# Requirement

### Tutorial create page

- As a ‘project manager’ user in Managers Dashboard, I should be able to create new tutorial
  - Considering that I am able to create new tutorial, I should be able to select the project type in the `Basic information` section. Project types being;
    - Build Area
    - Footprint
    - Change Detection
    - Completeness
  - Considering that I have selected ‘Build Area’, ‘Footprint’, or ‘Change Detection’, I should be able to interact and input in the ‘Basic information’ section. The ‘Basic information’ section includes
      - Name of the tutorial
      - Look for
    - I should be able to upload GeoJSON file
    - I should be able to interact and input in the ‘Information Screens’ section.
      - I should also be able to leave the ‘Information Screens’ section empty
      - The ‘Information Screens’ section includes;
        - Button to add and select the template for the information screen
          - 3 different types of templates;
            - 1 picture template. This includes;
              - Title of the image : text field. Limit of __ characters
              - Upload image : field to upload an image
              - Description of the image : text field. Limit of __ characters
            - 2 pictures templates. This includes;
              - Title of the first image : text field. Limit of __ characters
              - Upload image : field to upload an image
              - Description of first image : text field. Limit of __ characters
              - Title of the second image : text field. Limit of __ characters
              - Upload second image : field to upload an image
              - Description of second image : text field. Limit of __ characters
            - 3 pictures templates
              - Title of the first image : text field. Limit of __ characters
              - Upload first image : field to upload first image
              - Description of first image : text field. Limit of __ characters
              - Title of the second image : text field. Limit of __ characters
              - Upload second image : field to upload second image
              - Description of second image : text field. Limit of __ characters
              - Title of the third image : text field. Limit of __ characters
              - Upload the third image : field to upload third image
              - Description of third image : text field. Limit of __ characters
            - The number of information screens should be limited to __
            - Preview of the information screen
    - I should be able to interact and input in the ‘Scenarios’ section. The number of scenarios should be pulled from the GeoJson file we upload in the earlier step
      - This section includes;
        - ‘Instructions’ section
          - Title : text field. Limit of __ characters
          - Description : text field. Limit of __ characters
          - Icon : dropdown select option
        - ‘Hint’ section
          - Title : text field. Limit of __ characters
          - Description : text field. Limit of __ characters
          - Icon : dropdown select option
        - ‘Success’ section
          - Title : text field. Limit of __ characters
          - Description : text field. Limit of __ characters
          - Icon : dropdown select option
        - Preview section with options to choose between ‘Instructions’,
          ‘Hint’ and ‘Success’

### Tutorial view screen

- As a registered and logged-in user in the MapSwipe mobile app, I should be able to open any ‘Build area’, ‘Footprint’ or ‘Change Detection’ project from the Missions screen.
  - Considering that I have clicked on the ‘Tutorial’ button, I should be able to see the Instructions for this project
  - Considering that I have swiped past the Instructions screen, I should be able to see the Information Pages
    - *Condition: Instructions screen will only show if the ‘Instructions’ section has not been left empty during the tutorial creation
    - The information pages are created while creating the tutorial
    - The information pages will be shown based on the templates selected and inputs given while creating the tutorial
  - Considering that I have swiped past the Information Pages, I should be able to see the Scenario screens. The Scenario screens consists of;
    - Scenarios pulled from the GeoJson we uploaded while creating the ‘Build area’ project tutorial
      - Instruction’s title, description and icon for that scenario
      - Hint’s title, description and icon for that scenario
      - Success’s title, description and icon for that scenario
  - Considering that I have swiped past all the Scenario screens, I should be able to see an post-instruction screen
  - Considering that I have swiped past the post-instruction screen, I should be able to see ‘You’re ready to start MapSwipping!’ screen with ‘Start mapping’ button
    - If i click on the ‘Start mapping’ button, I should be directed back to the project details screen

# Issues

## Manager Dashboard

- [x] mapswipe/python-mapswipe-workers#830

### Tutorial Page: Information

- [x] mapswipe/python-mapswipe-workers#831
- [x] mapswipe/python-mapswipe-workers#832
- [x] mapswipe/python-mapswipe-workers#833
- [x] mapswipe/python-mapswipe-workers#834
- [x] mapswipe/python-mapswipe-workers#835
- [x] mapswipe/python-mapswipe-workers#836
- [x] mapswipe/python-mapswipe-workers#837
- [x] mapswipe/python-mapswipe-workers#838
- [x] mapswipe/python-mapswipe-workers#839

### Tutorial Page: Scenario

- [x] mapswipe/python-mapswipe-workers#840
- [x] mapswipe/python-mapswipe-workers#841
- [x] mapswipe/python-mapswipe-workers#843
- [x] mapswipe/python-mapswipe-workers#842
- [x] mapswipe/python-mapswipe-workers#844

## App

- [x] mapswipe/mapswipe#790
- [x] mapswipe/mapswipe#791
- [x] mapswipe/mapswipe#792
