### ISSUE TITLE
Footprint type mission for broader dataset validation

### ISSUE THREAD

**Issue by udaynwa** [mapswipe/python-mapswipe-workers#800]
# Requirement

### Tutorial create page

- As a ‘project manager’ user in Managers Dashboard, I should be able to create new ‘Footprint’ type tutorial
  - Considering that I am on the create new ‘Footprint’ type tutorial page, I should be able to see, interact and input in the ‘Options’ section. This section includes;
  - Options tabs
    - Title : text field. Limit of __ characters
    - Description : text field. Limit of __ characters
    - Icon : dropdown select option
    - Icon color : dropdown select option
    - Add option : button to add option. Limit of 2-6 options
    - Delete option : button to delete option
    - Sub-options
      - Add sub-options button
      - Description : text field. Limit of __ characters
      - Icon : dropdown select option
      - Add sub-option : button to add sub-option. Limit of 2-6 sub-options
      - Delete sub-option : button to delete sub-option
  - Add options button
    - Considering that i click the ‘Add option’ button, a new options tab should be created
  - Preview section of the options

### Project create page

- As a ‘project manager’ user in Managers Dashboard, I should be able to create new ‘Footprint’ type project
  - Considering that I have selected the ‘Footprint’ in Project Type, I should be able to select a tutorial for the project
  - Considering that I have selected a tutorial, the ‘Options’ section should be pulled and copied from the ‘Options’ section of the selected tutorial 
    - Once all the properties are pulled, the ‘Options’ section for ‘Footprint’ type project section should be READ ONLY
    - This section includes;
    - Options tabs
      - Title : text field. Limit of __ characters
      - Description : text field. Limit of __ characters
      - Icon : dropdown select option
      - Icon color : dropdown select option
      - Sub-options
        - Add sub-options button
        - Description : text field. Limit of __ characters
        - Icon : dropdown select option

### Tutorial viewing screens

- As a registered and logged in user in the MapSwipe mobile app, I should be able to open any Footprint type tutorial from the Missions screen
  - Considering that I have clicked on the ‘Tutorial’ button, I should be able to see the Instructions for this project.
    - Instructions for the project should be pulled from the Options we created while creating the tutorial for Footprint type project. Instructions screen include;
    - Icons, icon’s color, title and description
  - Considering that I have swiped past the Instructions screen, I should be able to see the Information Pages
    - The information pages are created while creating the tutorial
    - The information pages will be shown based on the templates selected and inputs given while creating the tutorial
  - Considering that I have swiped past the Information pages, I should be able to see the Scenario screens. The scenario screens consist of;
    - Scenarios pulled from the GeoJson we uploaded while creating the ‘Footprint’ project tutorial
      - Instruction’s title, description and icon for that scenario
      - Hint’s title, description and icon for that scenario
      - Success’s title, description and icon for that scenario
      - Options created in this tutorial
        - Sub-options under the selected option
  - Considering that I have swiped past all the Scenario screens, I should be able to see an post-instruction screen
  - Considering that I have swiped past the post-instruction screen, I should be able to see ‘You’re ready to start MapSwipping!’ screen with ‘Start mapping’ button
    - If i click on the ‘Start mapping’ button, I should be directed back to the project details screen

### Project mapping screens

- As a registered and logged in user in the MapSwipe mobile app, I should be able to open any Footprint type project from the Missions screen
  - Considering that I have clicked on a Footprint type project, I should be directed to the project’s details screen where I should be able to see 2 buttons;
    - Tutorial
    - Map now
  - Considering that I have clicked on Map now button, I should be directed to the mapping screens
    - Considering that I am in the mapping screens, I should be able to see and click on the options for that project. Options are created while creating the project in the Managers Dashboard by the Project Manager user
      - Considering that I have clicked on an option, I should be able to see and click on the sub-options under that option (if sub-options have been created under that option)
      - Considering that I have clicked on an option and there are no sub-options created under that option, I should be directed to the next mapping screen
  - Considering that I have completed a session of the project, I should be directed to the ‘Great job! You finished this group’ screen.
    - I should also be able to see and click on 2 buttons. The buttons should be;
      - Complete Session button
      - Continue mapping button

# Issues

### Tutorial create page

- [x] mapswipe/python-mapswipe-workers#813
- [x] mapswipe/python-mapswipe-workers#814
- [x] mapswipe/python-mapswipe-workers#815
- [x] mapswipe/python-mapswipe-workers#816
- [x] mapswipe/python-mapswipe-workers#817
- [x] mapswipe/python-mapswipe-workers#818
- [x] mapswipe/python-mapswipe-workers#819
- [x] mapswipe/python-mapswipe-workers#820
- [x] mapswipe/python-mapswipe-workers#821
- [x] mapswipe/python-mapswipe-workers#822

### Project create page

- [x] mapswipe/python-mapswipe-workers#823
- [x] mapswipe/python-mapswipe-workers#824

### Tutorial page

- [x] mapswipe/mapswipe#786
- [x] mapswipe/mapswipe#787
- [x] mapswipe/mapswipe#788

### Mapping page

- [x] mapswipe/mapswipe#789

## Firebase

- [x] #829

## Server
